### ISSUE TITLE
venom produces inconsistent xml output

### ISSUE THREAD

**Issue by fsamin** [runabove/venom#24]
if a test failure trace contains `<` or `>` like `result.err: <nil>` xml output is not a valid xml file

**Comment by yesnault** [comment]
already fixed on master. Err att is now string. I'll add a check for all file content

**Comment by fsamin** [comment]
we have this problem on our integration tests

**Comment by yesnault** [comment]
after merged of @sguiheux this morning ?

**Comment by fsamin** [comment]
my bad, will check it

**Comment by yesnault** [comment]
stdout & stderr -> not in tc.failure, I'll add it (with escape check)
