### ISSUE TITLE
feat: support env variables in yaml

### ISSUE THREAD

**Issue by fsamin** [runabove/venom#26]
`
name: Title of TestSuite
testcases:
- name: TestCase with default value, exec cmd. Check if exit code != 1
  steps:
  - script: echo 'hello ${USER:-world}'
    type: exec
`

use `USER` env variable or replace by `world` if not set. This syntax is the bash syntax for variable manipulation

**Comment by sguiheux** [comment]
need for password

**Comment by yesnault** [comment]
Need is for getting env in exec executor. 
Content of script can begin with #!/bin/bash (this is default value), so bash syntax is already usable

**Comment by yesnault** [comment]
+ inject in "vars" too
+ remove them unneeded "aliases"

**Comment by fsamin** [comment]
okay, example with bash syntax in script step sucks. btw it's still a requirement to have a default for an unset variable
